services:
    alifaraji.randomtopics.listener:
        class: alifaraji\randomtopics\event\listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '@auth'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
